apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
      - name: banking-container
        image: <dockerhub-username>/banking-app:latest
        ports:
        - containerPort: 8080
